animal = "chanchito feliz"
print(animal.upper())
print(animal.lower())
print(animal.strip().capitalize())
print(animal.title())
print(animal.strip())
print(animal.rstrip())
print(animal.lstrip())
print(animal.find("liz"))
print(animal.replace("liz", "o"))
print("nch" in animal)
print("nch" not in animal)
